//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string NIC { get; set; }
        public Nullable<int> Course_id { get; set; }
        public Nullable<int> Batch_id { get; set; }
        public Nullable<int> Teliphone_No_ { get; set; }
    
        public virtual batch batch { get; set; }
        public virtual Course Course { get; set; }
    }
}
